### ISSUE TITLE
ESLint v8 Support @ijsto/eslint-config

### ISSUE THREAD

**Issue by rtritto** [ijsto/eslint-config#10] opened 2021-10-10 15:18 UTC
`eslint` version 8 was released and I got warning on install step.

## Step to reproduce
1. `yarn init -y`
2. `yarn set version berry`
3. `yarn add eslint @ijsto/eslint-config`

### Actual
```
...
➤ YN0060: │ test-eslint@workspace:. provides eslint (p05a5b) with version 8.0.0, which doesn't satisfy what @ijsto/eslint-config and some of its descendants request
...
```

### Expect
No warning in log

## Versions
`eslint`: 8.0.0
`@ijsto/eslint-config`: 4.1.6
----
# ⚠️ UPDATE:

This issue is confirmed and is a composite issue which requires for a wider ecosystem support for ESLint v8.

We are aware of this, we will monitor and update the codebase to provide support to ESLint v8 as soon as it's possible.

## Please see below for a tracker of the current progress (will be updated incrementally).

**Comment by ScottAgirs** [comment] 2021-10-12 12:03
> Support for ESLint v8 _eslint-plugin-import_ was relased in [v2.25.0](https://github.com/import-js/eslint-plugin-import/releases/tag/v2.25.0).

Thanks so much for the heads-up! Added to #11

**Comment by ScottAgirs** [comment] 2021-10-16 11:21
[SOLUTION/TRACKER](https://github.com/ijsto/eslint-config/issues/10#issuecomment-939931123) is updated with references.

**Comment by ScottAgirs** [comment] 2021-11-10 13:32
The latest version `4.2.7` seems to have addressed the issue.

If you run into any bug, please open a new issue and it will be addressed with a patch version.

**Comment by rtritto** [comment] 2021-11-10 22:33
After install (`yarn add eslint @ijsto/eslint-config`), I got:
```console
➤ YN0060: │ test-eslint@workspace:. provides eslint (pf3766) with version 8.2.0, which doesn't satisfy what @ijsto/eslint-config and some of its descendants request
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
```

`yarn explain peer-requirements pf3766`
```console
➤ YN0000: test-eslint@workspace:. provides eslint@npm:8.2.0 with version 8.2.0, which doesn't satisfy the following requirements:

➤ YN0000: @babel/eslint-parser@npm:7.16.0 [41e81]      → ^7.5.0 || ^8.0.0                                           ✓
➤ YN0000: @ijsto/eslint-config@npm:4.2.7 [0f3ca]       → ^7.25.0 || ^8.0.0                                          ✓
➤ YN0000: eslint-config-airbnb-base@npm:14.2.1 [943ee] → ^5.16.0 || ^6.8.0 || ^7.2.0                                ✘
➤ YN0000: eslint-config-airbnb@npm:18.2.1 [41e81]      → ^5.16.0 || ^6.8.0 || ^7.2.0                                ✘
➤ YN0000: eslint-config-prettier@npm:8.3.0 [41e81]     → >=7.0.0                                                    ✓
➤ YN0000: eslint-plugin-es@npm:3.0.1 [9598e]           → >=4.19.1                                                   ✓
➤ YN0000: eslint-plugin-import@npm:2.25.2 [41e81]      → ^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 || ^8                 ✓
➤ YN0000: eslint-plugin-jsx-a11y@npm:6.4.1 [41e81]     → ^3 || ^4 || ^5 || ^6 || ^7                                 ✘
➤ YN0000: eslint-plugin-node@npm:11.1.0 [41e81]        → >=5.16.0                                                   ✓
➤ YN0000: eslint-plugin-prettier@npm:4.0.0 [41e81]     → >=7.28.0                                                   ✓
➤ YN0000: eslint-plugin-react-hooks@npm:4.3.0 [41e81]  → ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0 || ^8.0.0-0 ✓
➤ YN0000: eslint-plugin-react@npm:7.27.0 [41e81]       → ^3 || ^4 || ^5 || ^6 || ^7 || ^8                           ✓

➤ YN0000: Note: these requirements start with @ijsto/eslint-config@npm:4.2.7 [0f3ca]
```
Plugins that doesn't still support Eslint v8:
- eslint-config-airbnb-base
- eslint-config-airbnb
- eslint-plugin-jsx-a11y

FYI @ScottAgirs

**Comment by ScottAgirs** [comment] 2021-11-11 09:23
@rtritto  thank you for reporting this. Strange, I cannot reproduce this on my end, could you please share your `package.json`?

If anyone else is experiencing same issue, please chime in

**Comment by rtritto** [comment] 2021-11-11 09:45
My _package.json_ only have `eslint` and `@ijsto/eslint-config` as dependencies.
`eslint-config-airbnb` v19.0.0 was released, simply update it in the _package.json_ of `@ijsto/eslint-config`.
`eslint-config-airbnb-base` is a dependency of `eslint-config-airbnb` (already updated in v19.0.0).

**Comment by ScottAgirs** [comment] 2021-11-11 09:50
@rtritto thank you for your feedback and help, merged with 2f092941203b4d94345e009e02f7648d47d1fce8.

Cheers,
Closing for now.

**Closed by ScottAgirs** 2021-11-11 09:50 UTC
Labels: [CONFIRMED]

**Comment by rtritto** [comment] 2021-11-11 10:31
@ScottAgirs I saw the commit, you should never change directly version of a dependency in _package.json_, you must use upgrade/update option command of the package manager (npm/yarn etc).
Please, delete yarn.lock and run `yarn install` to regenerate dependencies in the new yarn.lock.

**Comment by ScottAgirs** [comment] 2021-11-11 10:34
Hey @rtritto thanks again for the pointers - duly noted! I have few improvements in mind for this package, including proper semver release mechanism, that surely is no excuse not to do things in a proper way! :) 

If you're open to contributing and suggesting some improvements, please ping me on [twitter.com/scottagirs](https://twitter.com/scottagirs) - would love to chat!

Also please feel free to open a PR, if you find any areas for improvements/fixes.
